import "./globals.css";
import "./navbar.css"; // Import the new CSS file for navbar styling

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <NavBar />
        {children}
      </body>
    </html>
  );
}

function NavBar() {
  return (
    <nav className="navbar">
      <div className="nav-links">
        <a href="#">Blog</a>
        <a href="#">About Us</a>
        <a href="#">Support</a>
      </div>
      <a href="#" className="sign-in-btn">Sign In</a>
    </nav>
  );
}
